---
title: "Shiny Package in R"
author: "Emma McLarnon"
date: "15 February 2018"
output: 
  ioslides_presentation:
  widescreen: true
  incremental: true
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#Deskpro<-read.csv("DeskPro - sample.csv", header=T)
source("Deskpro_func.R")

```
###Introduction to Shiny package in R
---

\


#### What is Shiny?


\

---

####Step 1: Install Shiny 

\

You may also need to install additional tools such as shinythemes

\
---

```{r, include=T, echo=T,eval=F}
#you will need to install these packages if you haven't already done so:
install.packages("shiny") 
install.packages("shinythemes")
install.packages("shinydashboard")
library(shiny) # Main shiny features
library(shinythemes) # For applying the default themes to you dashboard 
library(shinydashboard) # This allows you to have a header and side panel (useful if you want your dashboard to have multiple pages)
```

---
 
```{r, echo=T, eval=T}

library(shiny)
# Define server logic required to draw a histogram
server <- function(input, output) {
    x    <- faithful[, 2] #defining variable x
     bins <- seq(min(x), max(x)) #defining variable bins
     
     output$distPlot <- renderPlot({
 hist(x, breaks = bins, col = 'darkgray', border = 'white')
     
   })
}
# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel(""),
      mainPanel(
         plotOutput("distPlot")
      )
   )

# Run the application 
shinyApp(ui = ui, server = server)
```
